// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserMgClient is the client API for UserMg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserMgClient interface {
	CreateUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error)
}

type userMgClient struct {
	cc grpc.ClientConnInterface
}

func NewUserMgClient(cc grpc.ClientConnInterface) UserMgClient {
	return &userMgClient{cc}
}

func (c *userMgClient) CreateUser(ctx context.Context, in *NewUser, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/usermg.UserMg/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserMgServer is the server API for UserMg service.
// All implementations must embed UnimplementedUserMgServer
// for forward compatibility
type UserMgServer interface {
	CreateUser(context.Context, *NewUser) (*User, error)
	mustEmbedUnimplementedUserMgServer()
}

// UnimplementedUserMgServer must be embedded to have forward compatible implementations.
type UnimplementedUserMgServer struct {
}

func (UnimplementedUserMgServer) CreateUser(context.Context, *NewUser) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserMgServer) mustEmbedUnimplementedUserMgServer() {}

// UnsafeUserMgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserMgServer will
// result in compilation errors.
type UnsafeUserMgServer interface {
	mustEmbedUnimplementedUserMgServer()
}

func RegisterUserMgServer(s grpc.ServiceRegistrar, srv UserMgServer) {
	s.RegisterService(&UserMg_ServiceDesc, srv)
}

func _UserMg_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserMgServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usermg.UserMg/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserMgServer).CreateUser(ctx, req.(*NewUser))
	}
	return interceptor(ctx, in, info, handler)
}

// UserMg_ServiceDesc is the grpc.ServiceDesc for UserMg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserMg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usermg.UserMg",
	HandlerType: (*UserMgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserMg_CreateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usermg.proto",
}
